---
- name: Install packages necessary for Rails hosting
  apt: pkg={{ item }} state=present
  with_items:
    - apache2
    - apache2-threaded-dev
    - autoconf
    - automake
    - bison
    - build-essential
    - curl
    - git
    - libapr1-dev
    - libcurl4-openssl-dev
    - libffi-dev
    - libgdbm-dev
    - libncurses5-dev
    - libssl-dev
    - libreadline6-dev
    - libtool
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - make
  tags:
    - packages

- name: Check if passenger gem is installed
  command: bash -lc 'gem list passenger -v 4.0.20 --installed'
  register: passenger_gem_is_installed
  ignore_errors: True

# Always explicitly install the version that we've tested
- name: Install passenger gem
  command: bash -lc 'gem install passenger -v 4.0.20'
  when: passenger_gem_is_installed|failed

- name: Check (messily) if mod_passenger has compiled
  command: bash -lc 'ls `passenger-install-apache2-module --snippet | grep passenger_module | cut -f 3 -d " "`'
  register: passenger_is_installed
  ignore_errors: True

- name: Compile mod_passenger
  command: bash -lc 'passenger-install-apache2-module -a'
  register: passenger_has_been_installed
  when: passenger_is_installed|failed

- name: configure apache for mod_passenger (get snippet)
  command: bash -lc 'passenger-install-apache2-module --snippet > /tmp/passenger.load'
  when: passenger_has_been_installed|success or passenger_is_installed|success

- name: configure apache for mod_passenger (copy snippet)
  command: cp /tmp/passenger.load /etc/apache2/mods-available/passenger.load
  when: passenger_has_been_installed|success or passenger_is_installed|success

- name: Enable Passenger module
  command: a2enmod passenger
  when: passenger_has_been_installed|success or passenger_is_installed|success
  notify:
  - restart apache
