# All authorization, but especially root stuff, should be handled from
# this file and not in any of the roles. Otherwise the roles become
# less reusable.
---
- hosts: ci2.zhdk.ch
  tasks:
  - name: Authorize root users for ci2.zhdk.ch
    authorized_key: user=root key="{{ item }}"
    with_file:
      - files/ssh_keys/rca.pub
      - files/ssh_keys/thomas.pub
      - files/ssh_keys/franco.pub
      - files/ssh_keys/sebastian.pub
      - files/ssh_keys/matus.pub

- hosts: ci.zhdk.ch
  tasks:
  - name: Authorize root users for ci.zhdk.ch
    authorized_key: user=root key="{{ item }}" state=present
    with_file:
      - files/ssh_keys/rca.pub
      - files/ssh_keys/thomas.pub
      - files/ssh_keys/franco.pub
      - files/ssh_keys/sebastian.pub
      - files/ssh_keys/matus.pub

- hosts: developer_vms
  tasks:
  - name: Root users for developer VMs
    authorized_key: user=root key="{{ item }}" state=present
    with_file:
      - files/ssh_keys/franco.pub
      - files/ssh_keys/matus.pub
      - files/ssh_keys/rca.pub
      - files/ssh_keys/sebastian.pub
      - files/ssh_keys/thomas.pub
  - name: developer users for developer VMs
    authorized_key: user=developer key="{{ item }}" state=present
    with_file:
      - files/ssh_keys/franco.pub
      - files/ssh_keys/matus.pub
      - files/ssh_keys/rca.pub
      - files/ssh_keys/sebastian.pub
      - files/ssh_keys/thomas.pub
