---
- hosts: ci_slaves
  roles:
    - servers/ci_slaves

- hosts: domina_ci_executors
  roles:
    - servers/domina_ci_executor

# The CI slaves need packages and stuff from Madek as well as leihs
  tasks:
    - include: roles/servers/madek/tasks/packages.yml
    - include: tasks/leihs_packages.yml
