---
- hosts: developer_vm_leihs
  roles:
    - servers/developer_vm_leihs
    - servers/mariadb
    - configuration/iceweasel_latest
    - binaries/chromedriver
    - binaries/phantomjs
    - servers/rails
