---
- name: Install packages required by Domina CI executor
  apt: pkg={{ item }} state=present
  with_items:
    - curl
    - python-mysqldb

- name: Make sure {{ user }} exists
  user: name={{ user }} shell=/bin/bash state=present

- name: Register rbenv_root
  sudo: True
  sudo_user: "{{ user }}"
  shell: echo $HOME/.rbenv
  register: rbenv_root

- name: Install Domina CI Executor using debuntu
  sudo: True
  sudo_user: "{{ user }}"
  command: chdir={{rbenv_root.stdout}} bash -l -c 'RBENV_ROOT={{ rbenv_root.stdout }} debuntu_ci_domina-ci-executor_install'

- name: Install Leiningen using debuntu
  sudo: True
  sudo_user: "{{ user }}"
  command: bash -l -c 'debuntu_jvm_leiningen_install'

- name: Give privileges to create leihs test databases to the domina MariaDB user
  mysql_user:
    name: domina
    password: domina
    priv: 'leihs_test%.*:ALL'

