---
- name: Install Debuntu dependencies
  apt: pkg={{ item }} state=installed
  with_items:
    - curl

- name: Install debuntu script into /usr/local/bin 
  template: src=debuntu_fun.sh.j2 dest=/usr/local/bin/debuntu_fun.sh mode=755
